ALTER TABLE IF EXISTS transaction ADD COLUMN IF NOT EXISTS account_id BIGINT;
ALTER TABLE IF EXISTS transaction ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE IF EXISTS transaction ADD COLUMN IF NOT EXISTS status VARCHAR(255);
ALTER TABLE IF EXISTS transaction ADD COLUMN IF NOT EXISTS type VARCHAR(255);
ALTER TABLE IF EXISTS transaction ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE IF EXISTS transaction ADD COLUMN IF NOT EXISTS amount NUMERIC(38,2);
ALTER TABLE IF EXISTS transaction ALTER COLUMN description DROP NOT NULL;
ALTER TABLE IF EXISTS transfers ADD COLUMN IF NOT EXISTS related_account_id BIGINT;
ALTER TABLE IF EXISTS transfers ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE IF EXISTS transfers ALTER COLUMN destination_transaction_id DROP NOT NULL;
ALTER TABLE IF EXISTS transfers ALTER COLUMN source_transaction_id DROP NOT NULL;
ALTER TABLE IF EXISTS payments ALTER COLUMN transaction_id DROP NOT NULL;
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS payment_category VARCHAR(50) DEFAULT 'OTROS';
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS related_account_id BIGINT;
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS payment_method_id BIGINT;
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS name VARCHAR(150);
UPDATE payments SET payment_category = 'OTROS' WHERE payment_category IS NULL;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(500) NOT NULL,
    type VARCHAR(50) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Configuración de eliminación en cascada para mantener la integridad referencial
ALTER TABLE IF EXISTS account DROP CONSTRAINT IF EXISTS fkra7xoi9wtlcq07tmoxxe5jrh4;
ALTER TABLE IF EXISTS account ADD CONSTRAINT fkra7xoi9wtlcq07tmoxxe5jrh4 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS contacts DROP CONSTRAINT IF EXISTS fkbwdla3daipku5af60p84menq5;
ALTER TABLE IF EXISTS contacts ADD CONSTRAINT fkbwdla3daipku5af60p84menq5 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS contacts DROP CONSTRAINT IF EXISTS fkna8bddygr3l3kq1imghgcskt8;
ALTER TABLE IF EXISTS contacts ADD CONSTRAINT fkna8bddygr3l3kq1imghgcskt8 FOREIGN KEY (contact_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS notifications DROP CONSTRAINT IF EXISTS fk9y21adhxn0ayjhfocscqox7bh;
ALTER TABLE IF EXISTS notifications ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS transaction DROP CONSTRAINT IF EXISTS fk6g20fcr3bhr6bihgy24rq1r1b;
ALTER TABLE IF EXISTS transaction DROP CONSTRAINT IF EXISTS fk25e716ukpqahttjt6c487lrer;
ALTER TABLE IF EXISTS transaction ADD CONSTRAINT fk25e716ukpqahttjt6c487lrer FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS transfers DROP CONSTRAINT IF EXISTS fk6541ls1ptav8edx3lq0wjk1rp;
ALTER TABLE IF EXISTS transfers ADD CONSTRAINT fk6541ls1ptav8edx3lq0wjk1rp FOREIGN KEY (related_account_id) REFERENCES account(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS transfers DROP CONSTRAINT IF EXISTS fkhe7refveunojsefp9ntgcgquj;
ALTER TABLE IF EXISTS transfers ADD CONSTRAINT fkhe7refveunojsefp9ntgcgquj FOREIGN KEY (id) REFERENCES transaction(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS fke8yu0v9cmfccb1k7jv5rg6m9e;
ALTER TABLE IF EXISTS payments ADD CONSTRAINT fke8yu0v9cmfccb1k7jv5rg6m9e FOREIGN KEY (related_account_id) REFERENCES account(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS payments DROP CONSTRAINT IF EXISTS fkamqsd02p8lw9q50h4dvkptk7w;
ALTER TABLE IF EXISTS payments ADD CONSTRAINT fkamqsd02p8lw9q50h4dvkptk7w FOREIGN KEY (id) REFERENCES transaction(id) ON DELETE CASCADE;

